name: pb_authenticator
description: "PB two-factor authentication app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter team dependencies
  intl: ^0.20.2

  # Flutter plugins
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.2.2


  # Internal
  pb_authenticator_totp:
    path: ./totp
  pb_authenticator_state:
    path: ./state

  # External
  barcode_scan2: 4.5.1
  provider: ^6.1.2
  introduction_screen: ^3.1.11
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - graphics/icon.png
