name: pb_authenticator_state
description: State for PB Authenticator.
version: 1.2.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  uuid: 4.4.0

  # Internal
  pb_authenticator_totp:
    path: ../totp

  sqflite: ^2.3.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
