name: pb_authenticator_totp
description: TOTP library used by pb_authenticator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.5
  protobuf: ^3.1.0
  fixnum: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
